name: Trigger auto deployment for gateway-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ gateway-api ]
    paths:
    - '**'
    - '.github/workflows/gateway-api-AutoDeployTrigger-92a13577-89d3-4f18-beb0-c7ea9ce2bc8a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.GATEWAYAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GATEWAYAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GATEWAYAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: meuacrcloud.azurecr.io
          registryUsername: ${{ secrets.GATEWAYAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GATEWAYAPI_REGISTRY_PASSWORD }}
          containerAppName: gateway-api
          resourceGroup: aulaCloud
          imageToBuild: meuacrcloud.azurecr.io/gateway-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


