name: Trigger auto deployment for notificacoes-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/notificacoes-service-AutoDeployTrigger-111e62ae-6ce5-4313-ad66-3c24447758eb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NOTIFICACOESSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NOTIFICACOESSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NOTIFICACOESSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: meuacrcloud.azurecr.io
          registryUsername: ${{ secrets.NOTIFICACOESSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NOTIFICACOESSERVICE_REGISTRY_PASSWORD }}
          containerAppName: notificacoes-service
          resourceGroup: aulaCloud
          imageToBuild: meuacrcloud.azurecr.io/notificacoes-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


